#!/bin/bash
echo "Starting Google ADK Voice Chatbot..."
export GOOGLE_API_KEY="YOUR_GOOGLE_API_KEY"
export GOOGLE_CSE_ID="YOUR_GOOGLE_CSE_ID"
export GOOGLE_CSE_API_KEY="YOUR_GOOGLE_CSE_API_KEY"
export OPENAI_API_KEY="YOUR_OPENAI_API_KEY"
export ELEVENLABS_API_KEY="YOUR_ELEVENLABS_API_KEY"
python3 app.py
